### ISSUE TITLE
export config naming

### ISSUE THREAD

**Issue by rondiplomatico** [OpenCMISS-Dependencies/gdcm-abi#2]
the gdcm libraries are currently exported as "gdcm-abi" instead of gdcm. consequently, remote installations wont pick up that installation. think this through and fix.

**Comment by hsorby** [comment]
This has been done because we have made some changes that we require for handling DICOM images, this has made our version subtly different to the standard package hence the name to help with identification.

**Comment by rondiplomatico** [comment]
done in current devel version. its all gdcm-abi now.
